@Ecommerce_HostAddress = http://localhost:8000/api

### Auth - Register
POST {{Ecommerce_HostAddress}}/auth/register
Content-Type: application/json

{
    "Name": "John Doe",
    "Email": "john.doe@example.com",
    "Password": "securepassword123"
}

### Auth - Login
POST {{Ecommerce_HostAddress}}/auth/login
Content-Type: application/json

{
    "Email": "john.doe@example.com",
    "Password": "securepassword123"
}


